spring:
  application:
    name: hackathon
  datasource:
    url: jdbc:mysql://localhost:3306/hackathon?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
jwt:
  local:
    secret-key: ${HACKATHON_SECRET_KEY}
    expiration: 3600000
    short-expiration: 300000
  sdu-pass:
    sdu-pass-secret: ${SDU_PASS_SECRET}
    salt: KOISHIKISHIKAWAIIKAWAIIKISSKISSLOVELY
    iteration-cound: 114514
    key-length: 256
hackathon:
  frontend-url:
  register-path:
  redirect-path:
  team-capacity: 5
